apiVersion: apps/v1
kind: Deployment
metadata:
  name:  zuul-api-gateway
  namespace: ms 
  labels:
    app:  zuul-api-gateway
spec:
  selector:
    matchLabels:
      app: zuul-api-gateway
  replicas: 1
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: zuul-api-gateway
    spec:
      containers: 
      - name: zuul-api-gateway
        image: deekshithsn/zuul
        ports:
        - containerPort:  9999

---

apiVersion: v1
kind: Service
metadata:
  name: zuul-service
  namespace: ms 
spec:
  selector:
    app: zuul-api-gateway
  type: NodePort
  ports:
  - name: zuul-service
    protocol: TCP
    port: 9999
    targetPort: 9999
    nodePort: 32470
      